[package]
name = "util"
version.workspace = true
edition.workspace = true
description.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true

[lib]
path = "src/utils.rs"
doctest = false

[dependencies]
