[package]
name = "quantum"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/quantum.rs"
doctest = false

[dependencies]
derive_more.workspace = true
once_cell.workspace = true
downcast-rs.workspace = true
